CC = g++
CFLAGS = -std=c++17 -Wall -g

PROGS = main1 main2 main3 main4

all: $(PROGS)

main1: main1.cpp
	$(CC) $(CFLAGS) -o main1 main1.cpp

main2: main2.cpp
	$(CC) $(CFLAGS) -o main2 main2.cpp

main3: main3.cpp
	$(CC) $(CFLAGS) -o main3 main3.cpp

main4: main4.cpp
	$(CC) $(CFLAGS) -o main4 main4.cpp

clean:
	rm -f $(PROGS)
